// Mode normalization maps - AI may return inconsistent names

const TRANSPORT_NORMAL: Record<string, string> = {
  car: "car_petrol",
  driving: "car_petrol",
  automobile: "car_petrol",
  petrol: "car_petrol",
  gasoline: "car_petrol",
  ev: "car_electric",
  electric_car: "car_electric",
  electric: "car_electric",
  hybrid: "car_hybrid",
  car_hybrid: "car_hybrid",
  subway: "train",
  metro: "train",
  train: "train",
  railway: "train",
  bus: "bus",
  bicycle: "bike",
  cycling: "bike",
  bike: "bike",
  walking: "walk",
  walk: "walk",
  motorcycle: "motorcycle",
  motorbike: "motorcycle",
  flight: "flight_short",
  plane: "flight_short",
  airplane: "flight_short",
  flight_short: "flight_short",
  flight_long: "flight_long",
  long_flight: "flight_long",
};

const FOOD_NORMAL: Record<string, string> = {
  burger: "beef",
  steak: "beef",
  hamburger: "beef",
  beef: "beef",
  lamb: "lamb",
  pork: "pork",
  bacon: "pork",
  ham: "pork",
  cheese: "cheese",
  chicken: "chicken",
  poultry: "chicken",
  turkey: "chicken",
  salmon: "fish",
  tuna: "fish",
  fish: "fish",
  seafood: "fish",
  shrimp: "fish",
  eggs: "eggs",
  egg: "eggs",
  rice: "rice",
  milk: "milk",
  dairy: "milk",
  yogurt: "milk",
  vegetables: "vegetables",
  veggies: "vegetables",
  salad: "vegetables",
  fruits: "fruits",
  fruit: "fruits",
  nuts: "nuts",
  almonds: "nuts",
  peanuts: "nuts",
};

const ENERGY_NORMAL: Record<string, string> = {
  air_conditioning: "ac_hour",
  ac: "ac_hour",
  aircon: "ac_hour",
  air_con: "ac_hour",
  electricity: "grid_electricity",
  power: "grid_electricity",
  grid: "grid_electricity",
  natural_gas: "natural_gas",
  gas: "natural_gas",
  heating: "heater_hour",
  heater: "heater_hour",
  heater_hour: "heater_hour",
  ac_hour: "ac_hour",
  dryer: "dryer_hour",
  dryer_hour: "dryer_hour",
  tumble_dryer: "dryer_hour",
  washing_machine: "washing_machine",
  laundry: "washing_machine",
  washer: "washing_machine",
};

const SHOPPING_NORMAL: Record<string, string> = {
  tshirt: "tshirt",
  t_shirt: "tshirt",
  shirt: "tshirt",
  jeans: "jeans",
  pants: "jeans",
  trousers: "jeans",
  shoes: "shoes",
  sneakers: "shoes",
  footwear: "shoes",
  smartphone: "smartphone",
  phone: "smartphone",
  mobile: "smartphone",
  laptop: "laptop",
  computer: "laptop",
  macbook: "laptop",
  furniture: "furniture",
  sofa: "furniture",
  table: "furniture",
  chair: "furniture",
};

const NORMALIZATION_MAP: Record<string, Record<string, string>> = {
  transport: TRANSPORT_NORMAL,
  food: FOOD_NORMAL,
  energy: ENERGY_NORMAL,
  shopping: SHOPPING_NORMAL,
};

export function normalizeMode(category: string, mode: string): string {
  const lower = mode.toLowerCase().trim();
  const categoryMap = NORMALIZATION_MAP[category];
  if (!categoryMap) return lower;
  return categoryMap[lower] ?? lower;
}
